[package]
name = "zia"
version = "0.1.0"
authors = ["Charles Johnson <charlesthomasjohnson0@gmail.com>"]

[lib]
name = "zia"
crate-type = ["lib"]

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
dotenv = "0.9.0"
